### ISSUE TITLE
tcpflow build error with openssl 1.1

### ISSUE THREAD

**Issue by fefe17** [simsong/tcpflow#163]
The build problem is in src/dfxml/src/hash_t.h, here is my patch.

diff --git a/src/hash_t.h b/src/hash_t.h
index 0f2331e..0da8e31 100644
--- a/src/hash_t.h
+++ b/src/hash_t.h
@@ -31,6 +31,7 @@
 #ifndef  HASH_T_H
 #define  HASH_T_H
 
+#include <new>
 #include <cstring>
 #include <cstdlib>
 
@@ -189,7 +190,7 @@ inline std::string digest_name<sha512_t>() {
 
 template<const EVP_MD *md(),size_t SIZE> 
 class hash_generator__ { 			/* generates the hash */
-    EVP_MD_CTX mdctx;	     /* the context for computing the value */
+    EVP_MD_CTX* mdctx;	     /* the context for computing the value */
     bool initialized;	       /* has the context been initialized? */
     bool finalized;
     /* Static function to determine if something is zero */
@@ -202,21 +203,22 @@ class hash_generator__ { 			/* generates the hash */
 public:
     int64_t hashed_bytes;
     /* This function takes advantage of the fact that different hash functions produce residues with different sizes */
-    hash_generator__():mdctx(),initialized(false),finalized(false),hashed_bytes(0){ }
+    hash_generator__():mdctx(nullptr),initialized(false),finalized(false),hashed_bytes(0){ }
     ~hash_generator__(){
 	release();
     }
     void release(){			/* free allocated memory */
 	if(initialized){
-	    EVP_MD_CTX_cleanup(&mdctx);
+	    EVP_MD_CTX_free(mdctx);
 	    initialized = false;
 	    hashed_bytes = 0;
 	}
     }
     void init(){
 	if(initialized==false){
-	    EVP_MD_CTX_init(&mdctx);
-	    EVP_DigestInit_ex(&mdctx, md(), NULL);
+	    mdctx = EVP_MD_CTX_new();
+	    if (!mdctx) throw std::bad_alloc();
+	    EVP_DigestInit_ex(mdctx, md(), NULL);
 	    initialized = true;
 	    finalized = false;
 	    hashed_bytes = 0;
@@ -228,7 +230,7 @@ public:
 	    std::cerr << "hashgen_t::update called after finalized\n";
 	    exit(1);
 	}
-	EVP_DigestUpdate(&mdctx,buf,bufsize);
+	EVP_DigestUpdate(mdctx,buf,bufsize);
 	hashed_bytes += bufsize;
     }
     hash__<md,SIZE> final() {
@@ -242,7 +244,7 @@ public:
 	}
 	hash__<md,SIZE> val;
 	unsigned int len = sizeof(val.digest);
-	EVP_DigestFinal(&mdctx,val.digest,&len);
+	EVP_DigestFinal(mdctx,val.digest,&len);
 	finalized = true;
 	return val;
     }

**Comment by simsong** [comment]
Hi. can you submit this as a pull request? 

I need to set up a continuous integration system...

**Comment by fefe17** [comment]
Oh, uh, I see, github ate my diff.
Well I tried to send it as txt attachment first, and github rejected that, too.

Can you please try wget https://ptrace.fefe.de/tcpflow.dif

I was hoping to avoid having to set up public git repositories for now.

**Comment by simsong** [comment]
Hi. The correct way to submit this is as a pull request. You fork the repo on github, then submit a pull request. 

See: https://yangsu.github.io/pull-request-tutorial/ <https://yangsu.github.io/pull-request-tutorial/>

**Comment by fefe17** [comment]
Uh, I'm a bit stumped now. I attempted to fork dfxml (which bootstrap.sh pulled in in tcpflow) to apply my patch and send a pull request, but it already has a similar patch in it. The version bootstrap.sh pulled in for me did not.

I don't know what happened, but note that the patch you have in there is calling EVP_MD_CTX_create() without checking whether it returned NULL (which it can do if malloc fails). Other than that, the patch already in your dfxml repository is like mine. Mine throws a std::bad_alloc exception if EVP_MD_CTX_create returns NULL.

**Comment by simsong** [comment]
dfxml is a submodule. git submodules point to a specific commit. It may be that what's actually needed is for a pull request to change the specific commit that tcpflow is pointing to.

I will try to build tcpflow tonight. Can you tell me which OS you are building on? My system does not have OpenSSL 1.1.

**Comment by fefe17** [comment]
I'm using a self-built Linux distro, something like Linux from Scratch.
It does not matter though, the new code should also build and work on other OpenSSL versions.

**Comment by simsong** [comment]
Yes, but I do not support self-built Linux distributions. Is there an officially supported Linux that includes OpenSSL 1.1?

**Comment by fefe17** [comment]
As far as I know, Debian unstable has OpenSSL 1.1 (but I'm not sure, I am happy with my distro).

Why would you not support self-built Linux distributions? As long as people are using only standard components, what is the difference?

And with something like OpenSSL, would you not expect all distributions to upgrade eventually, and be on interested in fixing problems before they "hit the fan"?

**Comment by simsong** [comment]
I don't support self-built Linux distributions because life is sort and I no longer have funding for this project. If you want to set me up a VM, I'll log into it and make it work.

**Comment by fefe17** [comment]
Well you don't need to support me at all. In fact from my point of view I was supporting you :-)

The current version of the dependency compiles OK with openssl 1.1, but your reference is apparently to an older version of it that does not work with openssl 1.1. Change the reference to the current version and all is good.

Thanks for your time!

**Comment by simsong** [comment]
Okay. Thanks for the pointer. I'll update the dependency. We really need to push out a new version.

**Comment by olibre** [comment]
Voilà the @fefe17's patch copy-pasted from https://ptrace.fefe.de/tcpflow.dif

```diff
diff --git a/src/hash_t.h b/src/hash_t.h
index 0f2331e..0da8e31 100644
--- a/src/hash_t.h
+++ b/src/hash_t.h
@@ -31,6 +31,7 @@
 #ifndef  HASH_T_H
 #define  HASH_T_H
 
+#include <new>
 #include <cstring>
 #include <cstdlib>
 
@@ -189,7 +190,7 @@ inline std::string digest_name<sha512_t>() {
 
 template<const EVP_MD *md(),size_t SIZE> 
 class hash_generator__ { 			/* generates the hash */
-    EVP_MD_CTX mdctx;	     /* the context for computing the value */
+    EVP_MD_CTX* mdctx;	     /* the context for computing the value */
     bool initialized;	       /* has the context been initialized? */
     bool finalized;
     /* Static function to determine if something is zero */
@@ -202,21 +203,22 @@ class hash_generator__ { 			/* generates the hash */
 public:
     int64_t hashed_bytes;
     /* This function takes advantage of the fact that different hash functions produce residues with different sizes */
-    hash_generator__():mdctx(),initialized(false),finalized(false),hashed_bytes(0){ }
+    hash_generator__():mdctx(nullptr),initialized(false),finalized(false),hashed_bytes(0){ }
     ~hash_generator__(){
 	release();
     }
     void release(){			/* free allocated memory */
 	if(initialized){
-	    EVP_MD_CTX_cleanup(&mdctx);
+	    EVP_MD_CTX_free(mdctx);
 	    initialized = false;
 	    hashed_bytes = 0;
 	}
     }
     void init(){
 	if(initialized==false){
-	    EVP_MD_CTX_init(&mdctx);
-	    EVP_DigestInit_ex(&mdctx, md(), NULL);
+	    mdctx = EVP_MD_CTX_new();
+	    if (!mdctx) throw std::bad_alloc();
+	    EVP_DigestInit_ex(mdctx, md(), NULL);
 	    initialized = true;
 	    finalized = false;
 	    hashed_bytes = 0;
@@ -228,7 +230,7 @@ public:
 	    std::cerr << "hashgen_t::update called after finalized\n";
 	    exit(1);
 	}
-	EVP_DigestUpdate(&mdctx,buf,bufsize);
+	EVP_DigestUpdate(mdctx,buf,bufsize);
 	hashed_bytes += bufsize;
     }
     hash__<md,SIZE> final() {
@@ -242,7 +244,7 @@ public:
 	}
 	hash__<md,SIZE> val;
 	unsigned int len = sizeof(val.digest);
-	EVP_DigestFinal(&mdctx,val.digest,&len);
+	EVP_DigestFinal(mdctx,val.digest,&len);
 	finalized = true;
 	return val;
     }

```

**Comment by simsong** [comment]
Can you submit this as a pull request?

(Sent from my laptop.)

__________________________
Simson L. Garfinkel
https://simson.net/
202-649-0029

**Comment by olibre** [comment]
Hi @simsong 

No need for a pull request because a similar patch has already been merged in October 2016 (9 months ago): https://github.com/simsong/dfxml/issues/16

The commit is: https://github.com/simsong/dfxml/commit/8198685d798f6f41b82b63a02f5d7bdd7af187b5

This is why @fefe17 has written:

> Uh, I'm a bit stumped now. I attempted to fork dfxml (which bootstrap.sh pulled in in tcpflow) to apply my patch and send a pull request, but it already has a similar patch in it. The version bootstrap.sh pulled in for me did not.
> 
> I don't know what happened, but note that the patch you have in there is calling EVP_MD_CTX_create() without checking whether it returned NULL (which it can do if malloc fails). Other than that, the patch already in your dfxml repository is like mine. Mine throws a std::bad_alloc exception if EVP_MD_CTX_create returns NULL.

If you prefer the @fefe17's patch that throws exception `std::bad_alloc` instead of to return `NULL`, I can create a pull request. Let me know.

However fixing [`src/dfxml`](https://github.com/simsong/dfxml) is useless as long as tcpflow master branch points to the very very old commit https://github.com/simsong/dfxml/commit/13a8cc22189a8336d16777f2897ada6ae2ee59de (June 2014, three years ago). tcpflow master branch is missing 68 commits !

Would you appreciate a pull request to update the tcpflow submodule pointers?  
This will change the current old [`src/dfxml`](https://github.com/simsong/dfxml) submodule pointer ([`13a8cc2`](https://github.com/simsong/dfxml/commit/13a8cc22189a8336d16777f2897ada6ae2ee59de)) in order to use the latest master branch commit ([`0627696`](https://github.com/simsong/dfxml/commit/0627696f60663ef0e7420869758fa42cd4c91c90)).

**Comment by simsong** [comment]
Okay. Well, I just tried to build dfxml on my Fedora 25 system and there are lots of weird compiler warnings, so I need to get rid of them.  It's using GCC version 6.3.1.  I've forgotten how much I love Fedora's bleeding edge.


(Sent from my laptop.)

__________________________
Simson L. Garfinkel
https://simson.net/
202-649-0029

**Comment by olibre** [comment]
Fedora 26 has been officially released today !
https://fedoraproject.org/wiki/Releases/26/Schedule
Fedora 26 is based on GCC-7 and Clang-4,
yet more warnings !
Have fun 😉 🏆 😃

**Comment by simsong** [comment]
So I should abandon Fedora 25 and move to 26? 
Probably.


(Sent from my laptop.)

__________________________
Simson L. Garfinkel
https://simson.net/
202-649-0029

**Comment by olibre** [comment]
If you appreciate the *Fedora's bleeding edge*, yes go ahead for F26 🚀

**Comment by simsong** [comment]
I do!

**Comment by simsong** [comment]
Comments:

>      void release(){			/* free allocated memory */
>  	if(initialized){
> -	    EVP_MD_CTX_cleanup(&mdctx);
> +	    EVP_MD_CTX_free(mdctx);
>  	    initialized = false;
>  	    hashed_bytes = 0;
>  	}
>      }

I think that we actually want to use EVP_MD_CTX_destroy(), rather than free().  The documentation states:

EVP_MD_CTX_destroy() cleans up digest context ctx and frees up the space allocated to it, it should be called only on a context created using EVP_MD_CTX_create().




>      void init(){
>  	if(initialized==false){
> -	    EVP_MD_CTX_init(&mdctx);
> -	    EVP_DigestInit_ex(&mdctx, md(), NULL);
> +	    mdctx = EVP_MD_CTX_new();

I think that we want EVP_MD_CTX_create(), not EVP_MD_CTX_new().

**Comment by olibre** [comment]
Dear @simsong 

On [OpenSSL man page](http://www.gsp.com/cgi-bin/man.cgi?topic=EVP_MD_CTX_new) we can read:

> `EVP_MD_CTX_create()` and `EVP_MD_CTX_destroy()` were renamed to `EVP_MD_CTX_new()` and `EVP_MD_CTX_free()` in OpenSSL 1.1.

However, I do not know if you want to keep compatibility with OpenSSL 1.0 (I mean using `EVP_MD_CTX_create` instead of `EVP_MD_CTX_free`)... 

OpenSSL 1.0 got some issues as the well-known [Heartbleed security bug](https://en.wikipedia.org/wiki/Heartbleed#Patch). But this last issue is fixed since OpenSSL 1.0.1g. Therefore you may want to keep compatibility with both OpenSSL 1.0 and OpenSSL 1.1... Let me know what you want.

**Comment by simsong** [comment]
Thanks. I will update the configure script to check for the new versions and use the old versions if not present. Heart bleed is not an issue for this program.


----
Sent from my phone.

On Jul 18, 2017, at 1:17 AM, O. Libre <notifications@github.com> wrote:

Dear @simsong

On OpenSSL man page we can read:

EVP_MD_CTX_create() and EVP_MD_CTX_destroy() were renamed to EVP_MD_CTX_new() and EVP_MD_CTX_free() in OpenSSL 1.1.

However, I do not know if you want to keep compatibility with OpenSSL 1.0 (I mean using EVP_MD_CTX_create instead of EVP_MD_CTX_free)...

OpenSSL 1.0 got some issues as the well-known Heartbleed security bug. But this last issue is fixed since OpenSSL 1.0.1g. Therefore you may want to keep compatibility with both OpenSSL 1.0 and OpenSSL 1.1... Let me know what you want.

**Comment by simsong** [comment]
Did you look at my branch? I want to turn the branch into the master soon. I can just move over some of the getopt_long stuff that you did,    Without copying your cod.


----
Sent from my phone.

On Jul 18, 2017, at 1:17 AM, O. Libre <notifications@github.com> wrote:

Dear @simsong

On OpenSSL man page we can read:

EVP_MD_CTX_create() and EVP_MD_CTX_destroy() were renamed to EVP_MD_CTX_new() and EVP_MD_CTX_free() in OpenSSL 1.1.

However, I do not know if you want to keep compatibility with OpenSSL 1.0 (I mean using EVP_MD_CTX_create instead of EVP_MD_CTX_free)...

OpenSSL 1.0 got some issues as the well-known Heartbleed security bug. But this last issue is fixed since OpenSSL 1.0.1g. Therefore you may want to keep compatibility with both OpenSSL 1.0 and OpenSSL 1.1... Let me know what you want.

**Comment by olibre** [comment]
Hi @simsong.  

I have just reviewed your commits on branch https://github.com/simsong/tcpflow/tree/slg-dev
You provided very good work, congratulations 🏆 Thank you.
I have not seen any mistakes.
Unfortunately I have no time to test your branch **slg-dev** in production at my company 😞 
Moreover your **droproot** implementation has diverged a bit from my initial implementation.

I will ask my IT managers what they want:

1. my company uses a private diverged branch (unmaintained)
2. my company maintains a private branch with more and more difficult merges (and regression risks)
3. my company publish their contributions and request a merge into upstream project
 
About the version, I would increment the minor number: 1.4.5 -> 1.5.0 
Because many new features have been added since 1.4.5 (42 commits in one year). 
If you deliver v1.4.6, people would think it is just bug-fix patch...

**Comment by simsong** [comment]
Hi,

It's not my droproot implementation; it's the droproot implementation from tcpdump. Therefore, it's the correct droproot root implementation.

Thank you for the recommendation to update to 1.5.0. We will do that.

I need to make sure that it builds with both OpenSSL 1.0 and OpenSSL 1.1. So we are not ready for 1.5.0 test yet, but we are getting closer.

Thanks again for your help.

Simson

**Comment by simsong** [comment]
Looks like we can close this one.
