### ISSUE TITLE
 i want to know if there is a version of centos7, bacause when build from source code,some error happens...

### ISSUE THREAD

**Issue by KAIKAIZHANG** [simsong/tcpflow#210]
![image](https://user-images.githubusercontent.com/16151674/69317373-cb50d280-0c75-11ea-8f06-a3dfffac680c.png)

**Comment by simsong** [comment]
Perhaps you should install git?

**Comment by Perlovka** [comment]
git will not work with 1.5.2.tar.gz, because it does not contain .git directory.
Could you release ready-to-build version, like v1.5.0? Thanks.

**Comment by simsong** [comment]
What do you mean that git will not work? You clone it from GitHub...


----
Sent from my phone.

> On Nov 29, 2019, at 12:57 AM, Michael Perlov <notifications@github.com> wrote:
> 

﻿
git will not work with 1.5.2.tar.gz, because it does not contain .git directory.
Could you release ready-to-build version, like v1.5.0? Thanks.

**Comment by Perlovka** [comment]
It is not a good practice to build releases using git clone.
You have a releases page https://github.com/simsong/tcpflow/releases

So peoples are expecting to just download a release tarball, unpack, ./configure && make to create distro package.
Just like with https://github.com/simsong/tcpflow/releases/download/tcpflow-1.5.0/tcpflow-1.5.0.tar.gz

1.5.2 release tarball is unusable, because it does not contain nor .git directory neither submodules, needed for bootstrap.sh
https://github.com/simsong/tcpflow/archive/tcpflow-1.5.2.tar.gz

**Comment by simsong** [comment]
Huh. I thought that I did a “make release” to create that release. 
Shouldn’t “make release” make a proper release?

**Comment by simsong** [comment]
I think that I figured out what is going on here. You assumed that I created https://github.com/simsong/tcpflow/archive/tcpflow-1.5.2.tar.gz. However, I did not create that. It is being created by a feature of github that automatically makes a .tar.gz file if you specify an archive. But that just downloads the files in the git repo as a tar file; it is not a release. Honestly, I don't even know where you found that URL. It is not mine; I did not publicize it..
