### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by ThiefMaster** [simsong/tcpflow#226]
Hey, I just noticed that the Gentoo ebuild for tcpflow is scheduled to be removed in a month due to lack of Python 3 support: https://bugs.gentoo.org/735392

I don't know if there's simply no updated version for Gentoo or if tcpflow itself still requires Python 2, but it would be great if someone could take care of this issue :)

**Comment by simsong** [comment]
Odd. Tcpflow doesn’t use or require python.


----
Sent from my phone.

On Sep 27, 2020, at 6:04 AM, Adrian <notifications@github.com> wrote:

﻿
Hey, I just noticed that the Gentoo ebuild for tcpflow is scheduled to be removed in a month due to lack of Python 3 support: https://bugs.gentoo.org/735392

I don't know if there's simply no updated version for Gentoo or if tcpflow itself still requires Python 2, but it would be great if someone could take care of this issue :)

**Comment by jer-gentoo** [comment]
`tcpflow` links against `libpython2` and this feature is currently not optional. Not finding `libpython2` is not fatal in `configure.ac`, but `src/Makefile.am` compiles `scan_python.cc` unconditionally.

**Comment by jer-gentoo** [comment]
> Odd. Tcpflow doesn’t use or require python.

https://github.com/simsong/tcpflow/commit/657ffeb1c08bb936942f5401369c2d45c3aad3d1

Yet it does. :-)

**Comment by simsong** [comment]
Huh. Okay. Well, that’s not important. We can just remove it if nobody wants to upgrade it.


----
Sent from my phone.

On Sep 27, 2020, at 8:02 AM, Jeroen Roovers <notifications@github.com> wrote:

﻿
Odd. Tcpflow doesn’t use or require python.

657ffeb

Yet it does. :-)
